version: '3.1'

services:
  frontend:
    build: ./frontend
    ports:
      - 8080:3000
    volumes:
      - ./frontend/app:/app
    # https://github.com/facebook/create-react-app/issues/8688#issuecomment-602110747
    stdin_open: true
